#!/bin/sh

# Constants
readonly BOLDWHITE=$(tput sgr0 && tput bold)
readonly GREEN=$(tput bold && tput setaf 2)
readonly NC=$(tput sgr0) # No color/turn off all tput attributes

# Functions
build_binary()
{
	(
		cd ../"$1" || exit
		make clean && make
	)
}

printstep()
{
	printf "%s==> %s%s%s\n" "${GREEN}" "${BOLDWHITE}" "$1" "${NC}"
}

# Script
if [ "$1" = "--valgrind" ]; then
	printstep "Building binaries as debug binaries..."
	build_binary "battery"
	build_binary "vpn"
	printf "\n"

	printstep "Running valgrind on battery binary..."
	valgrind --leak-check=full ../battery/battery
	printf "\n"

	printstep "Running valgrind on vpn binary..."
	valgrind --leak-check=full ../vpn/vpn

	exit 0
fi

printstep "Running shellcheck on all shell scripts..."
shellcheck ./*
printf "\n"

printstep "Running cppcheck on all source code files..."
cppcheck ../
printf "\n"

printstep "Running Sparse on battery.c..."
sparse -Wsparse-all ../battery/battery.c
printf "\n"

printstep "Running Sparse on vpn.c..."
sparse -Wsparse-all ../vpn/vpn.c
