#!/bin/bash
#
# Description: Script to build a release binary for all project
#              modules.
#
# Homepage: https://gitlab.com/krathalan/waybar-modules
#
# Copyright (C) 2019 krathalan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# -----------------------------------------
# -------------- Guidelines ---------------
# -----------------------------------------

# This script follows the Google Shell Style Guide: 
# https://google.github.io/styleguide/shell.xml

# This script uses shellcheck: https://www.shellcheck.net/

# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail

# -----------------------------------------
# ----------- Program variables -----------
# -----------------------------------------

readonly MODULESTOBUILD=("battery" "vpn")
shaSums=()

# Colors
readonly BOLD_WHITE=$(tput sgr0 && tput bold)
readonly GREEN=$(tput bold && tput setaf 2)
readonly NC=$(tput sgr0) # No color/turn off all tput attributes

# ----------------------------------------------
# --------------- User variables ---------------
# ----------------------------------------------

copyOnBuild=false

# -----------------------------------------
# --------------- Functions ---------------
# -----------------------------------------

build_binary()
{
	cd ../"$1" || return 1
	make clean > /dev/null
	make release

	if [[ "${copyOnBuild}" == true ]]; then
		print_step "Copying wbm_$1 to /usr/bin..."
		sudo cp "wbm_$1" /usr/bin/
	fi

	shaSums+=("$(sha256sum "wbm_$1")")
}

print_step()
{
	printf "\n%s==>%s %s%s\n" "${GREEN}" "${BOLD_WHITE}" "$1" "${NC}"
}

# --------------------------------------
# --------------- Script ---------------
# --------------------------------------

if [[ $# -gt 0 ]]; then
	if [[ $1 == "--copy" ]]; then
		copyOnBuild=true
	fi
fi

for module in "${MODULESTOBUILD[@]}"; do
	build_binary "${module}"
done

print_step "SHA256SUMS:"

for sum in "${shaSums[@]}"; do
	printf "%s\n" "${sum}"
done
